strategyAbi = [{
	"inputs": [{
		"internalType": "address",
		"name": "_output",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "_pool",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "_want",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "constructor"
}, {
	"constant": True,
	"inputs": [],
	"name": "balanceOf",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "balanceOfPendingReward",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "burnfee",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "callfee",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "controller",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "dai",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": False,
	"inputs": [],
	"name": "deposit",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "fee",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "getName",
	"outputs": [{
		"internalType": "string",
		"name": "",
		"type": "string"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "governance",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": False,
	"inputs": [],
	"name": "harvest",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [],
	"name": "init",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "max",
	"outputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "output",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "pool",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "uint256",
		"name": "_fee",
		"type": "uint256"
	}],
	"name": "setBurnFee",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "uint256",
		"name": "_fee",
		"type": "uint256"
	}],
	"name": "setCallFee",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "address",
		"name": "_controller",
		"type": "address"
	}],
	"name": "setController",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "uint256",
		"name": "_fee",
		"type": "uint256"
	}],
	"name": "setFee",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "address",
		"name": "_governance",
		"type": "address"
	}],
	"name": "setGovernance",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "address",
		"name": "_output",
		"type": "address"
	}, {
		"internalType": "address",
		"name": "_pool",
		"type": "address"
	}],
	"name": "setNewPool",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "address[]",
		"name": "_path",
		"type": "address[]"
	}],
	"name": "setSwapRouting",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": True,
	"inputs": [{
		"internalType": "uint256",
		"name": "",
		"type": "uint256"
	}],
	"name": "swapRouting",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "unirouter",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "want",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "weth",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "uint256",
		"name": "_amount",
		"type": "uint256"
	}],
	"name": "withdraw",
	"outputs": [],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [{
		"internalType": "contract IERC20",
		"name": "_asset",
		"type": "address"
	}],
	"name": "withdraw",
	"outputs": [{
		"internalType": "uint256",
		"name": "balance",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": False,
	"inputs": [],
	"name": "withdrawAll",
	"outputs": [{
		"internalType": "uint256",
		"name": "balance",
		"type": "uint256"
	}],
	"payable": False,
	"stateMutability": "nonpayable",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "ycrv",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}, {
	"constant": True,
	"inputs": [],
	"name": "yfii",
	"outputs": [{
		"internalType": "address",
		"name": "",
		"type": "address"
	}],
	"payable": False,
	"stateMutability": "view",
	"type": "function"
}]
