# Generated by Django 3.1.1 on 2020-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('signal', models.CharField(max_length=20, verbose_name='signal')),
                ('origin_price', models.BigIntegerField(verbose_name='原始价格')),
                ('roi_week', models.FloatField(verbose_name='roi_week')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
