# Generated by Django 3.1.1 on 2020-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0002_tokenjson_text_3pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenjson',
            name='text_farm',
            field=models.TextField(default=0, verbose_name='文本_farm'),
            preserve_default=False,
        ),
    ]
