# Generated by Django 3.1.1 on 2020-10-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abi', '0003_tokenjson_text_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenjson',
            name='text_lp',
            field=models.TextField(default=0, verbose_name='文本_lp'),
            preserve_default=False,
        ),
    ]
